bear <- read.csv("so fresh and so clean clean.csv", header = T)
colnames(bear)
str(bear)
levels(bear$Site)
levels(bear$E..coli.MPN.100ml)
which(bear$E..coli.MPN.100ml == "NA ")
levels(bear$Date)
levels(bear$Time)
levels(bear$Coliform.MPN.100ml)
which(bear$Coliform.MPN.100ml == "NA ")
levels(bear$Flow.Estimate)
which(bear$Flow.Estimate == "High ")
levels(bear$Conducitivity..S.cm3)
which(bear$Conducitivity..S.cm3 == "illegible")
levels(bear$ORP.mV)
which(bear$ORP.mV == " NA")
levels(bear$Precip)
length(which(bear$TN..mg.L > 0))
length(which(bear$TP..mg.L > 0))
